# Generated by Django 6.0.4 on 2026-04-25 19:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_test', '0002_eventlog_eventschedule_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooleanTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(blank=True, null=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Boolean Test',
                'verbose_name_plural': 'Boolean Tests',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('critical', 'Critical Priority')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
            ],
            options={
                'verbose_name': 'Choice Test',
                'verbose_name_plural': 'Choice Tests',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DateTimeComprehensiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_field', models.DateField()),
                ('time_field', models.TimeField()),
                ('datetime_field', models.DateTimeField()),
                ('auto_now_field', models.DateTimeField(auto_now=True)),
                ('auto_now_add_field', models.DateTimeField(auto_now_add=True)),
                ('optional_date', models.DateField(blank=True, null=True)),
                ('optional_time', models.TimeField(blank=True, null=True)),
                ('optional_datetime', models.DateTimeField(blank=True, null=True)),
                ('duration_field', models.DurationField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'DateTime Comprehensive Test',
                'verbose_name_plural': 'DateTime Comprehensive Tests',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='IdentifierModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uuid_field', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('slug_field', models.SlugField(unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('identifier', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Identifier Test',
                'verbose_name_plural': 'Identifier Tests',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NumberTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('integer_field', models.IntegerField(default=0)),
                ('positive_integer', models.PositiveIntegerField(default=1)),
                ('big_integer', models.BigIntegerField(default=0)),
                ('small_integer', models.SmallIntegerField(default=0)),
                ('decimal_field', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('float_field', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Number Test',
                'verbose_name_plural': 'Number Tests',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TextFieldsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('short_text', models.CharField(max_length=50)),
                ('medium_text', models.CharField(max_length=500)),
                ('long_text', models.TextField(blank=True, default='')),
                ('richtext_content', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Text Fields Test',
                'verbose_name_plural': 'Text Fields Tests',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='URLEmailFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('website_url', models.URLField(blank=True, default='')),
                ('backup_email', models.EmailField(blank=True, default='', max_length=254)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
            ],
            options={
                'verbose_name': 'URL Email File Test',
                'verbose_name_plural': 'URL Email File Tests',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='eventlog',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='log_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='RelationshipTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_tests', to='admin_test.author')),
                ('categories', models.ManyToManyField(blank=True, related_name='relationship_tests', to='admin_test.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='relationship_tests', to='admin_test.tag')),
            ],
            options={
                'verbose_name': 'Relationship Test',
                'verbose_name_plural': 'Relationship Tests',
                'ordering': ['-id'],
            },
        ),
    ]
